In [24]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [25]:
dataset = pd.read_csv('/Users/alvina/Desktop/GERMAN-CREDIT-PROCESSOR/https:/github.com/datagirl01/german-credit-processor/data/raw/german_credit.csv')

In [26]:
dataset.head()

Creditability  Account Balance  Duration of Credit (month)  \
0              1                1                          18   
1              1                1                           9   
2              1                2                          12   
3              1                1                          12   
4              1                1                          12   

   Payment Status of Previous Credit  Purpose  Credit Amount  \
0                                  4        2           1049   
1                                  4        0           2799   
2                                  2        9            841   
3                                  4        0           2122   
4                                  4        0           2171   

   Value Savings/Stocks  Length of current employment  Instalment per cent  \
0                     1                             2                    4   
1                     1                             3                    2   
2                     2                             4                    2   
3                     1                             3                    3   
4                     1                             3                    4   

   Sex & Marital Status  Guarantors  Duration in Current address  \
0                     2           1                            4   
1                     3           1                            2   
2                     2           1                            4   
3                     3           1                            2   
4                     3           1                            4   

   Most valuable available asset  Age (years)  Concurrent Credits  \
0                              2           21                   3   
1                              1           36                   3   
2                              1           23                   3   
3                              1           39                   3   
4                              2           38                   1   

   Type of apartment  No of Credits at this Bank  Occupation  \
0                  1                           1           3   
1                  1                           2           3   
2                  1                           1           2   
3                  1                           2           2   
4                  2                           2           2   

   No of dependents  Telephone  Foreign Worker  
0                 1          1               1  
1                 2          1               1  
2                 1          1               1  
3                 2          1               2  
4                 1          1               2

In [28]:
print("Label => Creditability")
print("Attributes => {}".format(dataset[1:].columns))

Label => Creditability
Attributes => Index(['Creditability', 'Account Balance', 'Duration of Credit (month)',
       'Payment Status of Previous Credit', 'Purpose', 'Credit Amount',
       'Value Savings/Stocks', 'Length of current employment',
       'Instalment per cent', 'Sex & Marital Status', 'Guarantors',
       'Duration in Current address', 'Most valuable available asset',
       'Age (years)', 'Concurrent Credits', 'Type of apartment',
       'No of Credits at this Bank', 'Occupation', 'No of dependents',
       'Telephone', 'Foreign Worker'],
      dtype='object')


In [29]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
Creditability                        1000 non-null int64
Account Balance                      1000 non-null int64
Duration of Credit (month)           1000 non-null int64
Payment Status of Previous Credit    1000 non-null int64
Purpose                              1000 non-null int64
Credit Amount                        1000 non-null int64
Value Savings/Stocks                 1000 non-null int64
Length of current employment         1000 non-null int64
Instalment per cent                  1000 non-null int64
Sex & Marital Status                 1000 non-null int64
Guarantors                           1000 non-null int64
Duration in Current address          1000 non-null int64
Most valuable available asset        1000 non-null int64
Age (years)                          1000 non-null int64
Concurrent Credits                   1000 non-null int64
Type of apartment                    10

In [34]:
print("Count of positive samples: ",len(dataset[dataset['Creditability']==1]))
print("Count of positive samples: ",len(dataset[dataset['Creditability']==0]))

Count of positive samples:  700
Count of positive samples:  300


### Drop colums considering correlation

In [276]:
dataset.columns

Index(['Creditability', 'Account Balance', 'Duration of Credit (month)',
       'Payment Status of Previous Credit', 'Purpose', 'Credit Amount',
       'Value Savings/Stocks', 'Length of current employment',
       'Instalment per cent', 'Sex & Marital Status', 'Guarantors',
       'Duration in Current address', 'Most valuable available asset',
       'Age (years)', 'Concurrent Credits', 'Type of apartment',
       'No of Credits at this Bank', 'Occupation', 'No of dependents',
       'Telephone', 'Foreign Worker'],
      dtype='object')

In [562]:
datasetNew = dataset.drop('Telephone',axis=1)
datasetNew = datasetNew.drop('Duration in Current address',axis=1)
datasetNew = datasetNew.drop('No of dependents',axis=1)
datasetNew

Creditability  Account Balance  Duration of Credit (month)  \
0                1                1                          18   
1                1                1                           9   
2                1                2                          12   
3                1                1                          12   
4                1                1                          12   
5                1                1                          10   
6                1                1                           8   
7                1                1                           6   
8                1                4                          18   
9                1                2                          24   
10               1                1                          11   
11               1                1                          30   
12               1                1                           6   
13               1                2                          48   
14               1                1                          18   
15               1                1                           6   
16               1                1                          11   
17               1                2                          18   
18               1                2                          36   
19               1                4                          11   
20               1                1                           6   
21               1                2                          12   
22               0                2                          36   
23               1                2                          12   
24               1                1                           6   
25               1                2                          11   
26               1                1                          12   
27               1                2                           9   
28               1                4                          15   
29               1                3                          42   
30               1                3                          30   
31               1                4                          36   
32               1                4                          36   
33               1                4                          24   
34               1                1                          15   
35               1                1                           6   
36               1                4                          12   
37               1                4                          12   
38               1                4                          18   
39               1                4                          24   
40               1                4                          12   
41               1                1                          24   
42               1                4                          18   
43               1                2                          24   
44               1                2                          18   
45               0                1                          18   
46               1                4                          24   
47               0                4                          18   
48               1                4                          24   
49               1                1                          24   
50               1                4                          12   
51               1                3                          36   
52               1                4                           9   
53               1                4                          12   
54               1                4                          24   
55               1                1                          12   
56               1                4                          12   
57               1                1                          15   
58               1                4                 

### Since the Count of positive and negative samples are not balanced we are going to split the dataset to train and test for both postive and negative creditabilities and then concat them together to obtain the final train and test datasets.

In [563]:
cred1_df = datasetNew[datasetNew['Creditability']==1]
cred0_df = datasetNew[datasetNew['Creditability']==0]

In [564]:
# Now we are splitting cred1_df and cred0_df using train_test_split from sklearn
from sklearn.model_selection import train_test_split

X1_attributes = cred1_df.iloc[:,1:]
X2_attributes = cred0_df.iloc[:,1:]

y1_label = cred1_df.iloc[:,0]
y2_label = cred0_df.iloc[:,0]

X1_train, X1_test, y1_train, y1_test = train_test_split(X1_attributes, y1_label, test_size = 0.20, random_state = 0)
X2_train, X2_test, y2_train, y2_test = train_test_split(X2_attributes, y2_label, test_size = 0.20, random_state = 0)

In [565]:
# Noe we concat the train and test split df's from above
X_train = pd.concat([X1_train, X2_train], axis=0)
X_test = pd.concat([X1_test, X2_test], axis=0)
y_train = pd.concat([y1_train, y2_train], axis=0)
y_test = pd.concat([y1_test, y2_test], axis=0)

## Using Naive Bayes Classifier

In [566]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [567]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [568]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 39,  21],
       [ 30, 110]])

In [569]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.745


In [570]:
score=pd.DataFrame(list(metrics.precision_recall_fscore_support(y_test,y_pred)),index=['Precision','Recall','F1-Score','Support']).T

In [571]:
score

Precision    Recall  F1-Score  Support
0   0.565217  0.650000  0.604651     60.0
1   0.839695  0.785714  0.811808    140.0

### Using Decison Tree Classifier

In [572]:
# Fitting Decision Tree Classification to the Training set
from sklearn.tree import DecisionTreeClassifier
classifierDT = DecisionTreeClassifier(random_state = 2)
classifierDT.fit(X_train, y_train)


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=2,
            splitter='best')

In [573]:
# Predicting the Test set results
y_pred = classifierDT.predict(X_test)

In [574]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 31,  29],
       [ 26, 114]])

In [575]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.725


In [576]:
score=pd.DataFrame(list(metrics.precision_recall_fscore_support(y_test,y_pred)),index=['Precision','Recall','F1-Score','Support']).T

In [578]:
score


Precision    Recall  F1-Score  Support
0   0.543860  0.516667  0.529915     60.0
1   0.797203  0.814286  0.805654    140.0

### Using Random Forest Classifier

In [579]:
#### Fitting Random Forest Classification to the Training set
from sklearn.ensemble import RandomForestClassifier
classifierRF = RandomForestClassifier(n_estimators = 350, max_depth=140, random_state = 89)
classifierRF.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=140, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=350, n_jobs=None,
            oob_score=False, random_state=89, verbose=0, warm_start=False)

In [580]:
# Predicting the Test set results
y_pred = classifierRF.predict(X_test)

In [581]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[ 37,  23],
       [ 12, 128]])

In [582]:
from sklearn import metrics
# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.825


In [583]:
score=pd.DataFrame(list(metrics.precision_recall_fscore_support(y_test,y_pred)),index=['Precision','Recall','F1-Score','Support']).T

In [561]:
score


Precision    Recall  F1-Score  Support
0   0.755102  0.616667  0.678899     60.0
1   0.847682  0.914286  0.879725    140.0